### ISSUE TITLE
Controllers refactoring

### ISSUE THREAD

**Issue by naydav** [magento/magento2-login-as-customer#10]
1) All actions MUST return the ResultInterface implementation.
Current implementation:
```
$this->_view->loadLayout();
$this->_setActiveMenu('Magento_LoginAsCustomer::login_button');
$title = __('Store View To Login In ');
$this->_view->getPage()->getConfig()->getTitle()->prepend($title);
$this->_addBreadcrumb($title, $title);
$this->_view->renderLayout();
```

Desire state example:
```
/** @var Page $resultPage */
        $resultPage = $this->resultFactory->create(ResultFactory::TYPE_PAGE);
        $resultPage->setActiveMenu('Engine_Location::location_city')
            ->addBreadcrumb(__('Cities'), __('List'));
        $resultPage->getConfig()->getTitle()->prepend(__('Manage Cities'));
        return $resultPage;
```

2)  Every action controller should implement one of `\Magento\Framework\App\Action\Http*ActionInterface`

3) Remove `strrev` functions

4) For ajax call should use `$request->isXmlHttpRequest()` instead of additional parameters

5) Add type hinting for return value

6) Add a short useful description for docblocks (shortly describe the responsibility of controller action)

**Comment by ihorvansach** [comment]
I started to work on this issue.

**Comment by naydav** [comment]
https://github.com/magento/magento2-login-as-customer/pull/21
