### ISSUE TITLE
Admin user is logged into the default website if customer registered on second website

### ISSUE THREAD

**Issue by VasylShvorak** [magento/magento2-login-as-customer#102]
### Preconditions (*)

1. Magento with Login As Customer extension

### Steps to reproduce (*)

1. Create second website, e.g. New Website
![image](https://user-images.githubusercontent.com/26908019/80357117-2751ff80-8883-11ea-83a6-7c392ec71f4a.png)
2. Set Stores->Configuration->Web->Url Options->Add Store Code to Urls=Yes
3. Set Stores->Configuration->Customer Configuration->Account Sharing Options->Share Customer Accounts=Per Website
4. Create customer on second website ("New Website")
5. Go to backend
6. Go to Customers->All Customers
7. Click Edit on existing customer that was created on second website ("New Website")
![image](https://user-images.githubusercontent.com/26908019/80358131-9f6cf500-8884-11ea-8334-1500015d1535.png)

### Expected result (*)

1. Admin is logged in as customer on the front end in the correct website

### Actual result (*)

1. Admin is logged in as customer into the default store for the Main Website 
![image](https://user-images.githubusercontent.com/26908019/80358202-b57ab580-8884-11ea-97c2-94218ee71607.png)

**Comment by engcom-Delta** [comment]
Could be related with https://github.com/magento/magento2-login-as-customer/issues/58

**Comment by ihorvansach** [comment]
Working on it

**Comment by naydav** [comment]
https://github.com/magento/magento2-login-as-customer/pull/148

**Comment by sdzhepa** [comment]
@engcom-Delta Could you please do QA for this issue?

**Comment by engcom-Delta** [comment]
:heavy_check_mark: Issue is fixed
Was tested with latest commit https://github.com/magento/magento2-login-as-customer/commit/b821c269e52e4039c24794ed8425d8138a334438
**Result:**

- Store View To Login To=Auto-Detection

![Peek 2020-05-13 10-47](https://user-images.githubusercontent.com/51681379/81806587-558f3a80-9525-11ea-8cd3-d76f6a744159.gif)

- Store View To Login To=Manual Selection

![Peek 2020-05-13 10-50](https://user-images.githubusercontent.com/51681379/81806618-5fb13900-9525-11ea-8481-44f40e84638d.gif)
