### ISSUE TITLE
Restrictions on Magento EE

### ISSUE THREAD

**Issue by ihorvansach** [magento/magento2-login-as-customer#124]
@sdzhepa, @naydav  

I'm creating this ticket as a reminder for necessary changes for Magento Commerce

1. In Original repo there was fixes for EE webrestrictions, when not logged in customer restricted from wisiting store page, this also restricted to login as a customer when admin was a guest on the storefront, Related files:
https://github.com/magefan/module-login-as-customer/blob/master/etc/webrestrictions.xml
https://github.com/magefan/module-login-as-customer/blob/master/etc/frontend/events.xml
https://github.com/magefan/module-login-as-customer/blob/master/Observer/WbsiterestrictionFrontendObserver.php

2. In ticket https://github.com/magento/magento2-login-as-customer/issues/56 whe have popup with the store switcher. Magento EE has ALC restrictions  in the admin panel by store views, so some admin users are able to manage only specific store view (website),so will need to make sure that on EE such users see only allowed store views in the selectbox, also need to add additional check for the Login adminhtml controller.

**Comment by sdzhepa** [comment]
Was checked 
related code was merged
