### ISSUE TITLE
[BUG] TypeError: strrev() expects parameter 1 to be string, object given

### ISSUE THREAD

**Issue by smoskaluk** [magento/magento2-login-as-customer#13]
### Preconditions (*)

1. Magento with extension 'Login as customer' installed
2. 'New Store View' created for Main Website Store 

### Steps to reproduce (*)

1. In Admin Configuration enable 'Login as customer' extension for  'New Store View'  and disable for 'Default Store View'

![LAC extension](https://user-images.githubusercontent.com/27818516/73933038-483e3080-48e4-11ea-812a-99950e6c799e.png)

2. Go to Storefront , select 'New Store View' and create new customer account
3. In Magento Admin go to Customers grid and click 'Login as customer' link for created customer

### Expected result (*)

1. You should sucessfully login into customer account on  'New Store View' 

### Actual result (*)

`TypeError: strrev() expects parameter 1 to be string, object given in pr2/app/code/Magento/LoginAsCustomer/Controller/Adminhtml/Login/Login.php:87 Stack trace: #0 pr2/app/code/Magento/LoginAsCustomer/Controller/Adminhtml/Login/Login.php(87): strrev(Object(Magento\Framework\Phrase)) #1 pr2/generated/code/Magento/LoginAsCustomer/Controller/Adminhtml/Login/Login/Interceptor.php(24): Magento\LoginAsCustomer\Controller\Adminhtml\Login\Login->execute() #2 pr2/lib/internal/Magento/Framework/App/Action/Action.php(107): Magento\LoginAsCustomer\Controller\Adminhtml\Login\Login\Interceptor->execute() #3 pr2/app/code/Magento/Backend/App/AbstractAction.php(231): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http)) #4  pr2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http)) #5 pr2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\LoginAsCustomer\Controller\Adminhtml\Login\Login\Interceptor->___callParent('dispatch', Array) #6 pr2/app/code/Magento/Backend/App/Action/Plugin/Authentication.php(143): Magento\LoginAsCustomer\Controller\Adminhtml\Login\Login\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http)) #7 pr2/lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\LoginAsCustomer\Controller\Adminhtml\Login\Login\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http)) #8 pr2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\LoginAsCustomer\Controller\Adminhtml\Login\Login\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http)) #9 pr2/generated/code/Magento/LoginAsCustomer/Controller/Adminhtml/Login/Login/Interceptor.php(52): Magento\LoginAsCustomer\Controller\Adminhtml\Login\Login\Interceptor->___callPlugins('dispatch', Array, NULL) #10 pr2/lib/internal/Magento/Framework/App/FrontController.php(162): Magento\LoginAsCustomer\Controller\Adminhtml\Login\Login\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http)) #11 pr2/lib/internal/Magento/Framework/App/FrontController.php(99): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Magento\LoginAsCustomer\Controller\Adminhtml\Login\Login\Interceptor)) #12 pr2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http)) #13 pr2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array) #14 pr2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http)) #15 pr2/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array) #16 pr2/lib/internal/Magento/Framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http)) #17 pr2/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch() #18 pr2/lib/internal/Magento/Framework/App/Bootstrap.php(260): Magento\Framework\App\Http\Interceptor->launch() #19 pr2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor)) #20 {main}
`

**Comment by naydav** [comment]
Should be fixed in https://github.com/magento/magento2-login-as-customer/pull/21

**Comment by engcom-Delta** [comment]
@naydav @sdzhepa 
In general, issue is fixed but expected result is blocked by issue https://github.com/magento/magento2-login-as-customer/issues/58

**Manual testing scenario:**
1. Create 'Second Store View' for Main Website Store
2. In Admin Configuration enable 'Login as customer' extension for 'Second Store View' and disable for 'Default Store View'

![image](https://user-images.githubusercontent.com/51681379/79841024-78fc1500-83bf-11ea-8691-3f11bd640e03.png)

![image](https://user-images.githubusercontent.com/51681379/79841048-844f4080-83bf-11ea-8843-3376a084e119.png)
3. Go to Storefront , select 'New Store View' and create new customer account
4. In Magento Admin go to Customers grid and click 'Login as customer' link for created customer

**Result** with last commit [9204ab7](https://github.com/magento/magento2-login-as-customer/commit/9204ab78f6f69cd1f8a0bf496a58fb36b3486eb5) according steps from this issue:
![image](https://user-images.githubusercontent.com/51681379/79840834-27ec2100-83bf-11ea-898f-ada214858e2d.png)

**Comment by engcom-Delta** [comment]
Closed as such case will not be available according https://github.com/magento/magento2-login-as-customer/issues/16
