### ISSUE TITLE
Admin login as customer with id=1

### ISSUE THREAD

**Issue by VasylShvorak** [magento/magento2-login-as-customer#133]
### Preconditions (*)

1. Magento [2.4-develop](https://github.com/magento/magento2/commit/b1ef766d69780896a0b58e393b6b98a5d85f8279)
2. Login As Customer is enabled
3. Few customers are created

### Steps to reproduce (*)

1. Go to Customers->All Customers
2. Click Edit on existing customer with id not equal `1`
3. Click Login as Customer

### Expected result (*)

1. Admin is logged in as current customer

### Actual result (*)

1. Admin is logged in as customer with id=1
![Peek 2020-05-04 11-21](https://user-images.githubusercontent.com/26908019/80948426-b8ccee80-8dfa-11ea-9b97-8ea3fae0d251.gif)

**Comment by engcom-Delta** [comment]
Issue is not reproducible with latest commit 6b6f428
