### ISSUE TITLE
Login as Customer not working if store view code is added to url.

### ISSUE THREAD

**Issue by engcom-Foxtrot** [magento/magento2-login-as-customer#134]
### Preconditions (*)

1. Login as Customer enabled.
2. Login as Customer store view selection is set to auto-detection.
3. Add Store Code to Urls enabled.
4. Customer created.

### Steps to reproduce (*)

1. Open Customer page on the backend.
2. Try to Login as Customer.

### Expected result (*)

1. Login successful.

### Actual result (*)

1. Error 404.

**Comment by naydav** [comment]
https://github.com/magento/magento2-login-as-customer/pull/135

**Comment by naydav** [comment]
https://github.com/magento/magento2-login-as-customer/pull/148

**Comment by sdzhepa** [comment]
@engcom-Delta Could you please do QA for this issue?

**Comment by engcom-Delta** [comment]
:heavy_check_mark: Issue is fixed
Was tested with latest commit https://github.com/magento/magento2-login-as-customer/commit/b821c269e52e4039c24794ed8425d8138a334438
**Result:**

- Store View To Login To=Auto-Detection

![Peek 2020-05-13 10-09](https://user-images.githubusercontent.com/51681379/81782753-f3254280-9502-11ea-8037-88a6ddae6f0b.gif)

- Store View To Login To=Manual Selection

![Peek 2020-05-13 10-12](https://user-images.githubusercontent.com/51681379/81782788-033d2200-9503-11ea-9ef8-945b22760686.gif)
