### ISSUE TITLE
Login as Customer Log is available when Login as Customer is disabled.

### ISSUE THREAD

**Issue by engcom-Foxtrot** [magento/magento2-login-as-customer#136]
### Preconditions (*)

1. Login As Customer extension is disabled.

### Steps to reproduce (*)

1. Navigate to Customers -> Customers in admin menu
2. Open Login as Customer Log page ([Magento instance]/admin/loginascustomer_log/log/index/)

### Expected result (*)

1.  Login as Customer Log menu item is not shown
2. Login as Customer Log is not accessible.

### Actual result (*)

1. Menu item Login as Customer Log is shown
2. Login as Customer Log is accessible.

**Comment by naydav** [comment]
https://github.com/magento/magento2-login-as-customer/pull/139
