### ISSUE TITLE
Login as Customer incorrect popup message.

### ISSUE THREAD

**Issue by engcom-Foxtrot** [magento/magento2-login-as-customer#137]
### Preconditions (*)

1. Login as Customer enabled.
2. Customer created.

### Steps to reproduce (*)

1. Open Customer page on the backend.
2. Try to Login as Customer.

### Expected result (*)

1. Login as Customer popup has some correct message.

### Actual result (*)

1. Login as Customer popup has "undefined" message.

**Comment by naydav** [comment]
https://github.com/magento/magento2-login-as-customer/pull/142/files

**Comment by sdzhepa** [comment]
QA additionally tested on

### Current Cloud Magento alpha9 2.4.0
- this issue is already fixed. tested on both pop-up windows(Auto/manual)
