### ISSUE TITLE
Spinner/Loader should appear before page content

### ISSUE THREAD

**Issue by sdzhepa** [magento/magento2-login-as-customer#145]
### Steps to reproduce (*)

1. Go to Admin Panel
2. Open any Customer edit page and click "Login as Customer" button

### Expected result (*)
1. According to UX design  Loader should appear before page content is displayed 
![loader_login_as_customer](https://user-images.githubusercontent.com/50657230/80600594-ea297100-8a2c-11ea-9de8-2d669b38d85f.gif)

### Actual result (*)

1. The page displays content for a couple of seconds and only after loader is shown
![loader QA](https://user-images.githubusercontent.com/3409584/81201269-b6010380-8f8a-11ea-9b74-489c9f20af84.gif)

**Comment by naydav** [comment]
https://github.com/magento/magento2-login-as-customer/pull/147
