### ISSUE TITLE
Banner disappear when admin edit customer data from Account Information tab

### ISSUE THREAD

**Issue by engcom-Delta** [magento/magento2-login-as-customer#156]
### Preconditions (*)

1. Magento 2.4-develop
2. Login as Customer is enabled
3. Customer 'John Doe' is created

### Steps to reproduce (*)

1. Go to Magento Admin -> Customers -> All Customers and open customer 'John Doe' account to edit
2. Click on Login as Customer
3. Go to Account Information
4. Edit First Name
5. Click Save

### Expected result (*)

1. Banner should be displayed on all pages

### Actual result (*)

1. Banner is not shown after save
![Peek 2020-05-26 17-07](https://user-images.githubusercontent.com/51681379/82912039-41abf580-9f75-11ea-92cb-6913156a3ec9.gif)

**Comment by sdzhepa** [comment]
### Test this issue on the PR https://github.com/magento/magento2-login-as-customer/pull/162

- Banner still showing after change customer information

But Customer name and Website Name in the banner is changed to **undefined**
![2020-06-16_15-11-44](https://user-images.githubusercontent.com/3409584/84823711-67f90a00-afe4-11ea-9ebd-2f7f872bea99.jpg)

**Comment by sdzhepa** [comment]
### Test this issue on the PR https://github.com/magento/magento2-login-as-customer/pull/163

QA Passed: https://github.com/magento/magento2-login-as-customer/pull/163#issuecomment-642464449

Additionally was tested: Issue with UNDEFINED name and Website is not repro on this PR

**Comment by naydav** [comment]
https://github.com/magento/magento2-login-as-customer/pull/163
