### ISSUE TITLE
[B2B+EE]Exception error when admin click on Login as Customer link

### ISSUE THREAD

**Issue by engcom-Delta** [magento/magento2-login-as-customer#157]
### Preconditions (*)

1. Magento 2.4-develop+EE 2.4-develop + B2B 1.2-develop
2. Login as Customer is enabled
3. Customer 'John Doe' is created

### Steps to reproduce (*)

1. Go to Magento Admin -> Customers -> All Customers and open customer 'John Doe' account to edit
2. Click on Login as Customer

### Expected result (*)

1. Admin user should be redirected to storefront and logged in as customer 'John Doe' 

### Actual result (*)

1. Exception error:
`TypeError: Argument 1 passed to Magento\LoginAsCustomer\Model\AuthenticateCustomerBySecret::execute() must be of the type string, object given, called in /var/www/html/magento2dev/lib/internal/Magento/Framework/Interception/Interceptor.php on line 58 and defined in /var/www/html/magento2dev/app/code/Magento/LoginAsCustomer/Model/AuthenticateCustomerBySecret.php:47`

### Proposed solution:
In `\Magento\LoginAsCustomerLogging\Plugin\LoginAsCustomerApi\LogAuthenticationPlugin::aroundExecute` should be `$proceed($secret)` instead of `$proceed($authenticationData)`

**Comment by engcom-Foxtrot** [comment]
https://github.com/magento/partners-magento2ee/pull/265#issuecomment-640763886

**Comment by lenaorobei** [comment]
Delivered to 2.4.0-develop.
