### ISSUE TITLE
Enable Page Cache - Admin is not logged in as customer because was redirected to the "Sign In" page

### ISSUE THREAD

**Issue by engcom-Lima** [magento/magento2-login-as-customer#158]
### Preconditions (*)

1. Magento 2.4-develop
2. Login as Customer is enabled
3. Customer 'John Doe' is created

### Steps to reproduce (*)

1. Go to Stores -> Configuration -> Customers -> Login as Customer -> Login as Customer Settings
2. Set 'Disable Page Cache For Admin User ' to "No"
3. Save
4. Go to  Customers -> All Customers
5. Click on "Login As Customer" link for customer  'John Doe' 
6. Click "Login As Customer" 

### Expected result (*)

1.  Admin is redirected to Storefront and logged in 'John Doe' account
![Screenshot_35](https://user-images.githubusercontent.com/60198022/83363343-7ff44b00-a3a1-11ea-8cf5-b48dd65bb41b.png)

### Actual result (*)

1. Admin is not logged in as customer because was redirected to the "Sign In" page
![Screenshot_34](https://user-images.githubusercontent.com/60198022/83363276-df059000-a3a0-11ea-90d3-74a55ebb69e1.png)

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

Result
![Screenshot_71](https://user-images.githubusercontent.com/60198022/84505598-af228a80-acc6-11ea-8cbd-6beb7ec9ba9d.png)

**Comment by naydav** [comment]
https://github.com/magento/magento2-login-as-customer/pull/165
