### ISSUE TITLE
Error is shown on the page if customer is not sign out from account 

### ISSUE THREAD

**Issue by engcom-Lima** [magento/magento2-login-as-customer#159]
**NOTE:** 
1. The issue happens only if we use one browser with Admin Session and logged in a Customer session. (in one tab Customer is logged in from Storefront, in the second tab Admin tries to Login as Customer as this customer)
1.1 If refresh page(F5) Admin successfully logged in(but seems additional empty quote is created and stored in DB)

2. If using different browsers issue will not repro

### Preconditions (*)

1. Magento 2.4-develop
2. Login as Customer is enabled
3. Customer 'John Doe' is created

### Steps to reproduce (*)

1. Go to StoreView and login as 'John Doe' 
2. Place Order 
3. Go to Admin
4. Edit the customer 'John Doe' 
5. Click on "Login As Customer" link for customer 'John Doe'
6. Click "Login As Customer"

### Expected result (*)

1.  Admin redirected on the Account page
2. No error

### Actual result (*)

1. Admin redirected on the Home page
2. Error "No such entity with cartId = 7" is shown
![2020-06-0130](https://user-images.githubusercontent.com/60198022/83415515-d4daa480-a427-11ea-8d21-0192fb3637b0.gif)

**Comment by sdzhepa** [comment]
TEsted on https://github.com/magento/magento2-login-as-customer/issues/159

QA Passed

tested initial case and small workaround

**Comment by naydav** [comment]
https://github.com/magento/magento2-login-as-customer/pull/164
