### ISSUE TITLE
All System Configuration settings should be on Global level

### ISSUE THREAD

**Issue by sdzhepa** [magento/magento2-login-as-customer#16]
Currently, all settings related to "Login as Customer"  functionality  in the Configuration  are on "storeview" level but should be on the GLOBAL

### Steps to reproduce
1. Login to Magento Admin panel
2. Go to STORES > Configuration
3. Open section CUSTOMERS > Login As Customer

### Expected result:
- all settings on Global level

###  Actual Result
![image](https://user-images.githubusercontent.com/3409584/74379930-44138680-4dae-11ea-95c2-3740e461c3a2.png)

**Comment by ihorvansach** [comment]
Working on it

**Comment by naydav** [comment]
https://github.com/magento/magento2-login-as-customer/pull/22

**Comment by engcom-Delta** [comment]
@naydav @sdzhepa 
Issue is reproducible with last commit [9204ab7](https://github.com/magento/magento2-login-as-customer/commit/9204ab78f6f69cd1f8a0bf496a58fb36b3486eb5)
![image](https://user-images.githubusercontent.com/51681379/79844800-d5adfe80-83c4-11ea-97d6-a235f6e23c57.png)

![image](https://user-images.githubusercontent.com/51681379/79844854-ec545580-83c4-11ea-819f-43d0cdbcb423.png)
