### ISSUE TITLE
[CE] Endless loading of the page after trying to search any word in "Login as Customer Log"

### ISSUE THREAD

**Issue by engcom-Lima** [magento/magento2-login-as-customer#168]
As a fix before release input for search by keywords was removed.
Admin still able to search using filter functionality  

### Preconditions (*)

Note: reproducible on in Open Sorce(CE) edition. On Logging page/grid for Login as Customer

1. Magento 2.4-develop
2. Login as Customer is enabled

### Steps to reproduce (*)

1. Go to Customers -> Login as Customer Log
2. Type any word in Search field
3. Press Enter 

### Expected result (*)

1. No error
2. Search Results displayed

### Actual result (*)

1. Alert with the "Something went wrong" error is shown 
2. Endless loading of the page
After refreshing page the same behavior 
![Peek 2020-06-15 11-50](https://user-images.githubusercontent.com/60198022/84645138-cfda2280-af08-11ea-8086-94f78214be5c.gif)

**Comment by sdzhepa** [comment]
@naydav @sdzhepa 

need to define requirements
do we need it at all? what fields should be searchable

**Comment by naydav** [comment]
The full-text search functionality was disabled until clarifying requirements.
