### ISSUE TITLE
Notification banner on storefront

### ISSUE THREAD

**Issue by sdzhepa** [magento/magento2-login-as-customer#17]
As a merchant admin user I want to be notified in a clear way when I log in to customer accounts so that I can maintain awareness of which account I am viewing on the storefront.

**Business Value**
Because merchant admin users can make destructive and significant changes to user accounts when logged in as customers, it's important to provide persistent notification in the browser of which customer account they are viewing.

**Assumptions and Notes**
 * Consider a similar approach to existing [Demo Store](https://docs.magento.com/m2/ce/user_guide/design/demo-notice.html) feature

**AC**
* **all UX design:** [UX_LoginAsCustomer_March_12_3_2020.pdf](https://github.com/magento/magento2-login-as-customer/files/4325537/UX_LoginAsCustomer_March_12_3_2020.pdf)
* **Additional Banner Design Details PDF** : [BannerAdditionalDesignDetails.pdf](https://github.com/magento/magento2-login-as-customer/files/4388646/BannerAdditionalDesignDetails.pdf)
* **Adobe Mock up**  [MockUp link](https://xd.adobe.com/view/7c1347fc-d229-4afc-5ee7-1c53bdaec588-0a22/) 

 * When admin user logs in to a customer account, persistent banner/message is shown in the browser
* No UI elements require in SysConfig. (widgets, cms, etc) “only in code”
 * Appearance of banner/message based on approved UX design
 * Wording for message on banner based on approved UX design and Technical Writer review: : "Banner text: _You are connected as **Benny the Buyer** on [Website]_"
 * Appearance of banner can be modified by storefront theme

**UX Details**

1. Banner general view 
![banner](https://user-images.githubusercontent.com/3409584/76880596-e3141e00-6845-11ea-81e4-dce185680d44.png)
**Banner text**: You are connected as [$CustomerName] on [$Website]
* $CustomerName = {Customer First Name} + {Customer Last Name}
* $Website = {Website Title}

**CTA: Close Session(x)** After click should be next:
* the session is "killed" and becomes a guest session
* The banner is not showing
* page with "You are signed out" is shown like in other cases when Custore signed out

**Demo Steps**
 1. As a merchant admin user, log in to a customer account using Login as Customer
 1. Verify banner is displayed based on approved UX design
 1. Verify correct message is displayed based on approved message from Technical Writer
 1. Take additional actions in storefront:
     1. View product detail page
     1. View category page
     1. View wishlist
     1. View cart
     1. Add item to cart
     1. Place order
 1. Verify banner is persistent and appears during all page views in session

**Comment by ihorvansach** [comment]
Working on it

**Comment by ihorvansach** [comment]
@sdzhepa , I have created pull request
https://github.com/magento/magento2-login-as-customer/pull/47

I need approved UX design and message text. Right now it uses the same design as demo notice (https://docs.magento.com/m2/ce/user_guide/design/demo-notice.html) and text:

Attention! You are logged in as the customer.

**Comment by sdzhepa** [comment]
Hello @ihorvansach 

I just found that some requirements could be missed in the description of this issue.
I am going to review and update this issue and also will add additional UX information.

Sorry for possible inconveniences

**Comment by sdzhepa** [comment]
@mbrinton01  could you please review added requirements and confirm it from PO side?

@ihorvansach please looks through the updates. Does it have all the required information from DEV perspective?

**Comment by ihorvansach** [comment]
@sdzhepa , could you please specify what is "general Image for banner" ?

**Comment by mbrinton01** [comment]
@sdzhepa requirements are confirmed. If any questions, please ask them here. 
@ihorvansach "General image for banner" just means the mockup that @sdzhepa attached here. It shows what the banner should look like at the top of the screen when an Admin user is Logged in to a Customer storefront account.

**Comment by ihorvansach** [comment]
@sdzhepa , I have updated merge request (made changes for the UX) https://github.com/magento/magento2-login-as-customer/pull/47 

Can anyone review the code?

**Comment by sdzhepa** [comment]
@ihorvansach  thank you for the update. I requested @naydav for code-review

**Comment by sdzhepa** [comment]
FYI

@ihorvansach  

Added additional details for banner [BannerAdditionalDesignDetails.pdf](https://github.com/magento/magento2-login-as-customer/files/4388646/BannerAdditionalDesignDetails.pdf)

**Comment by ihorvansach** [comment]
Thank you @sdzhepa , I have made style adjustments, they're available in PR.

**Comment by naydav** [comment]
https://github.com/magento/magento2-login-as-customer/pull/47

**Comment by engcom-Delta** [comment]
@naydav @sdzhepa 
Issue is reproducible with latest commit [9204ab7](https://github.com/magento/magento2-login-as-customer/commit/9204ab78f6f69cd1f8a0bf496a58fb36b3486eb5) (The banner is not showing)

![image](https://user-images.githubusercontent.com/51681379/79860765-ecac1b00-83db-11ea-9b06-92e54f3e1ecd.png)

**Comment by ihorvansach** [comment]
@naydav , @sdzhepa , I've made a fix.

**Comment by engcom-Delta** [comment]
Issue is not reproducible with latest commit [bb6103e](https://github.com/magento/magento2-login-as-customer/commit/bb6103e52fce7dcae2c12451d643d23bed145d80)

Result:
![Peek 2020-04-24 11-44](https://user-images.githubusercontent.com/51681379/80201512-ecef2500-862c-11ea-8ad9-3591bda9e4f1.gif)

**Comment by engcom-Delta** [comment]
Closed as fixed
