### ISSUE TITLE
Any order placed by admin when logged in as customer must be logged as created by the admin

### ISSUE THREAD

**Issue by sdzhepa** [magento/magento2-login-as-customer#18]
### Requirements:
1. Any order placed by admin when logged in as customer must be logged as created by the admin
a). This should be visible both on frontend order status and admin panel order detail
b). This should be visible as API response for GET order detail
c). Current "create order from Admin Panel" functionality also needs to be added to the same log. Orders created from the admin panel must log the user who created the order.

### User Scenario 1.a 
1. Admin, logged in as customer Placed Order

**Expected Results in Admin Panel on Order Details page:**
- Information that order was placed by admin should be in "Notes for this Order"
- Text message: [not approved yet] "This order has been placed by admin(? user name|First Name|Last Name| First Last Name)"
![image](https://user-images.githubusercontent.com/3409584/74386096-bee29e80-4dba-11ea-9a7a-6c2a185e5d51.png)

**Expected Results on Storefront, Customer Order review page:**
![image](https://user-images.githubusercontent.com/3409584/74386170-eb96b600-4dba-11ea-91bd-321c117bc372.png)

**Comment by naydav** [comment]
Closed in favor of https://github.com/magento/magento2-login-as-customer/issues/28
