### ISSUE TITLE
When admin logs out of admin account, all existing "login as customer" sessions must also be logged out at the same time

### ISSUE THREAD

**Issue by sdzhepa** [magento/magento2-login-as-customer#19]
### Requirements:
•	When admin logs out of admin account, all existing "login as customer" sessions must also be logged out at the same time
--	Pending architecture design for how to enforce this. For example, may be acceptable to force log out when any next action/page load is attempted in the "login as customer" session

### Example user scenario
1. Admin User signed-in to Admin Panel
2. Admin click "Login as Customer" button
**RESULT:** NEW browser page is opened and signed in as a customer
3. Admin user Logout from Admin Panel
**RESULT:**  session for the customer must also be logged out at the same time

**Comment by naydav** [comment]
Closed in favor of https://github.com/magento/magento2-login-as-customer/issues/29
