### ISSUE TITLE
Move changes from Magefan Login As Customer added after Jan 9 2020

### ISSUE THREAD

**Issue by ihorvansach** [magento/magento2-login-as-customer#20]
Once `https://github.com/magefan/module-login-as-customer` was merged into the app/code/Magento/LoginAsCustomer in it's original repo there where several changes (commits). Need to check all of them starts after Jan 9, 2020 and move code to Magento_LoginAsCustomer
https://github.com/magefan/module-login-as-customer/commits/master

**Pay attention to this one**, it fixes the security issue:
https://github.com/magefan/module-login-as-customer/commit/1da0bcef0f811a27aa1783c1e9e3595aa065f4e9

**Comment by ihorvansach** [comment]
@naydav, I have checked and this is done. All necessary changes present in https://github.com/magento/magento2-login-as-customer/tree/module-login-as-customer

**Comment by sdzhepa** [comment]
@naydav 
close this ticket based on prev https://github.com/magento/magento2-login-as-customer/issues/20#issuecomment-622063129
