### ISSUE TITLE
Remove MageFan and update Copyright

### ISSUE THREAD

**Issue by naydav** [magento/magento2-login-as-customer#25]
All versions of Magento should have the correct code attribution and copyright.

AC:
- All references to 'MageFan' are removed from code, labels, and code comments
- If needed, copyright for imported code is updated
- If needed, license for imported code is updated
- MageFan is recognized for extension contribution in Release Notes for Login as Customer Feature

Demo Steps:
- In IDE, verify all references to 'MageFan' have been removed from code
- Demonstrate correct copyright in new module
- Demonstrate correct license in new module
- Demonstrate Release Notes

**Comment by ihorvansach** [comment]
@naydav , @sdzhepa ,

I think that once these current pull requests will be processed:
https://github.com/magento/magento2-login-as-customer/pull/21
https://github.com/magento/magento2-login-as-customer/pull/22
https://github.com/magento/magento2-login-as-customer/pull/23

Then can check this ticket.
