### ISSUE TITLE
Admin order noted in Order Comments

### ISSUE THREAD

**Issue by naydav** [magento/magento2-login-as-customer#28]
As a customer I want to see when orders have been created on my behalf so that I clearly understand the source of all orders in my account.

As a merchant I want to see when orders have been created by admins on behalf of customers so that I can follow the creation history of any order.

Assumptions and Notes
 * Order Comment API exists and can be used to GET and POST Order Comments
 * Merchants do not want to reveal the name of customer service reps or other admin users to customers in order comments that are visible on the storefront or in email notifications to customers

AC
* **UX design:** [UX_LoginAsCustomer_March_12_3_2020.pdf](https://github.com/magento/magento2-login-as-customer/files/4325537/UX_LoginAsCustomer_March_12_3_2020.pdf)
 * When an order is placed by an admin who is logged in as a customer, two order comments are added:

|Purpose|comment|`is*visible_on_front`|`is_customer*notified`|
|---|---|---|---|
|Allows customer to view that order was placed on their behalf when viewing order detail on the storefront|Order Placed by Store Administrator|`yes`|`no`|
|Allows merchant to view which admin user placed order on customer's behalf when viewing order detail from the admin panel|Order Placed by `<admin user full name>` using Login as Customer|`no`|`no`|

 * Order comments are viewable on storefront and in admin depending on `is*visible_on*front` setting for each comment (this behavior already exists)
 * When an order is placed by an admin *through the admin panel,* two order comments are added (nice to have):

|Purpose|comment|`is*visible_on_front`|`is_customer*notified`|
|---|---|---|---|
|Allows customer to view that order was placed on their behalf when viewing order detail on the storefront|Order Placed by Store Administrator|`yes`|`no`|
|Allows merchant to view which admin user placed order on customer's behalf when viewing order detail from the admin panel|Order Placed by `<admin user full name>` using Admin Panel|`no`|`no`|

 * Order Comments can be retrieved with REST GET endpoint: `GET    /V1/orders/:id/comments`

Demo Steps
 1. <AUTOMATED> As merchant admin, login as a customer
 1. [AUTOMATED] Create order on behalf of customer
 1. [AUTOMATED] View order detail in storefront my account. Verify that order comment is visible with correct message and timestamp.
 1. [AUTOMATED] View order detail in admin panel. Verify that order comment is visible with correct message and timestamp.
 1. [AUTOMATED] GET Order Comments for the order using REST API. Verify that order comment has correct message and timestamp.
 1. As merchant admin, create order for a customer from the admin panel
 1. View order detail in admin panel. Verify that order comment is visible with correct message and timestamp.
 1. Login as the customer and view order detail in storefront my account. Verify that order comment is visible with correct message and timestamp.

**Comment by sdzhepa** [comment]
Hello @engcom-Foxtrot and @naydav 

Here are notes from the grooming meeting about MVP(must-have for 2.4.0) part of this task.
Please review, probably we can split this task for several and focus only on MVP


Admin order noted in Order Comments
- [ not MVP for 2.4.0 need to Split ] "_When an order is placed by an admin through the admin panel, an order comment is added such as 'Order Placed by Store Administrator' with timestamp of order placement (nice to have)". looks like it should be CORE logic improvements_
- [not MVP for 2.4.0] “GraphQL does not support order comments from store”
- [not MVP for 2.4.0**] Can be created separate story for “Any changes to email notifications when orders are created on behalf of customers”
- **[MVP for 2.4.0]** _AC: “When an order is placed by an admin who is logged in as a customer, an order comment is added such as 'Order Placed by Store Administrator' with timestamp of order placement”_
- **[MVP for 2.4.0]** _AC: “Order comments are viewable on storefront and in admin (this behavior already exists)”_
- **[MVP for 2.4.0]** _AC: “Order Comments can be retrieved with REST GET endpoint: GET /V1/orders/:id/comments”_

**Comment by naydav** [comment]
https://github.com/magento/magento2-login-as-customer/pull/66

**Comment by engcom-Delta** [comment]
:heavy_check_mark: Issue is fixed
Result with latest commit [9204ab7](https://github.com/magento/magento2-login-as-customer/commit/9204ab78f6f69cd1f8a0bf496a58fb36b3486eb5)

![image](https://user-images.githubusercontent.com/51681379/79862673-1d418400-83df-11ea-9964-6af021f07221.png)

![image](https://user-images.githubusercontent.com/51681379/79862755-3e09d980-83df-11ea-90dd-dc5c8113c63d.png)

GET /V1/orders/:id/comments
![image](https://user-images.githubusercontent.com/51681379/79864504-3dbf0d80-83e2-11ea-8a16-a2c304790b0a.png)
