### ISSUE TITLE
[QA] Login as Customer from Admin Panel (verification)

### ISSUE THREAD

**Issue by naydav** [magento/magento2-login-as-customer#30]
Need to verify that after merging of the initial module we have:

As a merchant admin user I want to login to customer accounts from the admin panel so that I can assist customers with browsing, purchasing, and resolving site issues.

**Business Value**
To enable merchant admin users to assist customers who are only able to browse the storefront, these admin users need the ability to log in to specific customer accounts.

**AC**
 * Merchant admin users can log in as customers from the admin panel
 * No possibility for admin users to access, view, or store/save customer passwords. All login happens only through button click from admin panel.
 * Button/Link (depends on approved UX design) is visible on the following pages in the admin panel:
             * Customer Edit page
             * Order View page
             * Invoice View page
             * Shipment View page
             * Credit Memo View page
 * Button/Link *does not appear* for any pages related to guest orders:
             * Order View page
             * Invoice View page
             * Shipment View page
             * Credit Memo View page 

**Demo Steps**
 1. <span style="color:#00875a"><AUTOMATED></span> Login to admin panel as admin user
 1. <span style="color:#00875a">[AUTOMATED]</span> Open customer edit page for a customer account
 1. <span style="color:#00875a">[AUTOMATED]</span> Verify 'Login as Customer' button/link is available. Click on button
 1. <span style="color:#00875a">[AUTOMATED]</span> Verify storefront session is opened in separate tab/window 
 1. <span style="color:#00875a">[AUTOMATED]</span> Verify storefront session is for the correct customer
 1. <span style="color:#00875a">[AUTOMATED]</span> Verify storefront session begins on customer dashboard (My Account)
 1. <span style="color:#00875a"><AUTOMATED></span> Repeat demo steps 3-6 for the following pages:
             * Order View page
             * Invoice View page
             * Shipment View page
             * Credit Memo View page
 1. Open Order View page for a guest checkout order
 1. Verify 'Login as Customer' button/link does not appear

**Comment by engcom-Delta** [comment]
Verification results:
**AC**
 * No possibility for admin users to access, view, or store/save customer passwords. All login happens only through button click from admin panel. - **Result:** current implementation allow admin to access and save customer password - [ **no dev task created** ]
![image](https://user-images.githubusercontent.com/51681379/78005410-31481780-7344-11ea-92f3-5ee19c410eb3.png)

**Demo Steps**
 1. <span style="color:#00875a">[AUTOMATED]</span> Verify storefront session is for the correct customer - **Result:** current session is same for customer and admin - [ **dev tasks** ]: https://github.com/magento/magento2-login-as-customer/issues/17, https://github.com/magento/magento2-login-as-customer/issues/29
![image](https://user-images.githubusercontent.com/51681379/78006546-d44d6100-7345-11ea-917b-4be31255b938.png)

 1. <span style="color:#00875a">[AUTOMATED]</span> Verify storefront session begins on customer dashboard (My Account) - **Result:** home page is shown, session begins on `loginascustomer/login/proceed/` page - [ **no dev task created** ]
![image](https://user-images.githubusercontent.com/51681379/78006876-3908bb80-7346-11ea-8590-c15d9efe6aa2.png)

 1. <span style="color:#00875a"><AUTOMATED></span> Repeat demo steps 3-6 for the following pages:
             * Order View page
             * Invoice View page
             * Shipment View page
             * Credit Memo View page
- **Result:** home page is shown, session begins on `loginascustomer/login/proceed/` page - [ **no dev task created** ]
![image](https://user-images.githubusercontent.com/51681379/78006876-3908bb80-7346-11ea-8590-c15d9efe6aa2.png)

**Comment by sdzhepa** [comment]
Hello @engcom-Delta 

Thank you for your verification!

It seems I did not get your point for the : 
> 2. [AUTOMATED] Verify storefront session begins on customer dashboard (My Account) - Result: home page is shown, session begins on loginascustomer/login/proceed/ page - [ no dev task created ]
> 3. Repeat demo steps 3-6 for the following pages: ...

Do we need any additional task(s) for development or it already covered in https://github.com/magento/magento2-login-as-customer/issues/17 and https://github.com/magento/magento2-login-as-customer/issues/17


And about AC:

> No possibility for admin users to access, view, or store/save customer passwords. All login happens only through button click from admin panel. - Result: current implementation allow admin to access and save customer password - [ no dev task created ]

I think it is ok, to reset customer password in My Account should be entered OLD password.
- Admin is not able to get current customer password from My Account
- Admin is not able to change(set new)  password
- + Admin is not able to change customers email address without current password

@mbrinton01 could you please confirm current behavior for this AC? Is it OK or we need additional chnages

**Comment by mbrinton01** [comment]
These are correct in your comment above. We don't need additional things. We can keep the current password behavior (admin cannot set new password, admin cannot change email without password) and also ensure admin cannot get password from the account.

**Comment by engcom-Delta** [comment]
@naydav @sdzhepa 
Issues https://github.com/magento/magento2-login-as-customer/issues/17, https://github.com/magento/magento2-login-as-customer/issues/29 are still reproducible with latest commit [9204ab7](https://github.com/magento/magento2-login-as-customer/commit/9204ab78f6f69cd1f8a0bf496a58fb36b3486eb5)

**Comment by sdzhepa** [comment]
All issues from https://github.com/magento/magento2-login-as-customer/issues/30#issuecomment-617207565  are completed.
This ticket can be closed
