### ISSUE TITLE
[QA] ACL for Login as Customer (verification)

### ISSUE THREAD

**Issue by naydav** [magento/magento2-login-as-customer#31]
Need to verify that after merging of the initial module we have:

As a merchant, I want to control which admin users can Log in as a Customer so that I maintain full control over what actions my employees can take in the admin panel.

**Current State**
In the MageFan extension, there are ACL settings for Login as Customer. Most of the AC of this story is already covered, but needs to be verified.

**Business Value**
To maintain appropriate security over what actions are possible for each admin user role, merchants must be able to restrict admin user roles from logging in to customer accounts via the admin panel.

**AC**
 * ACL permission exists for Login as Customer. This permission controls whether the role can use the Login as Customer feature in the admin.
             * If permission is not granted, Login as Customer button/link does not appear anywhere in the admin for the assigned role
             * Permission located under Customers>Login as Customer
 * ACL permission exists for Login as Customer settings. This permission controls whether the role can manage settings for Login as Customer.
             * Permission located under Stores>Configuration>Login as Customer
             * If permission is not granted, assigned admin role cannot modify any settings for Login as Customer
 * ACL permission exists for viewing Login as Customer log. This permission controls whether the role can view the Login as Customer log in the admin.
             * If permission is not granted, assigned admin role cannot view the Login as Customer log
             * View log permission only applies to Open Source edition. In Commerce, Login as Customer log is not displayed because all actions are logged in the Admin Actions Report.
 * ACL permissions are responsive to Role Scope settings 
             * If customer accounts are global, admin users with Login as Customer permission can log in as any customer
             * If customer accounts are per website, admin users with Login as Customer permission can log in as any customer with an account on the website(s) the admin user has permissions for

**Demo Steps**
 1. Log in to admin panel as admin user
 1. Verify ACL permission for Login as Customer is created per UX design
 1. Verify ACL permission for Viewing Login as Customer log is created per UX design
 1. Verify ACL permission for Login as Customer Configuration is created per UX design
 1. Assign all permissions to an admin role
 1. Verify assigned admin role can take all expected actions:
     1. Login as Customer
     1. Modify Login as Customer configuration
     1. View Login as Customer log 
 1. Remove all permissions for an admin role
 1. Verify assigned admin role does not have all expected actions:
     1. Login as Customer (not visible)
     1. Modify Login as Customer configuration (not possible)
     1. View Login as Customer log (not visible)
 1. Assign Login as Customer permission to an admin role for a single website
     1. Verify assigned admin role can Login as Customer for accounts assigned to the relevant website
     1. Verify assigned admin role can not Login as Customer for accounts assigned to any other website

**Comment by engcom-Delta** [comment]
Verification results:

**Demo Steps**
 1. Verify ACL permission for Login as Customer is created per UX design - **Result:** current design `Login As Customer Button` - [ **dev task** ]: https://github.com/magento/magento2-login-as-customer/issues/54
![image](https://user-images.githubusercontent.com/51681379/78022492-b12eab80-735d-11ea-80bf-fca079baa448.png)

 1. Verify ACL permission for Viewing Login as Customer log is created per UX design - **Result:** current design `Login As Customer Log` - [ **dev task** ]: https://github.com/magento/magento2-login-as-customer/issues/54
![image](https://user-images.githubusercontent.com/51681379/78022492-b12eab80-735d-11ea-80bf-fca079baa448.png)

 1. Verify ACL permission for Login as Customer Configuration is created per UX design - **Result:** current design `Login As Customer Section` - [ **dev task** ]: https://github.com/magento/magento2-login-as-customer/issues/54
![image](https://user-images.githubusercontent.com/51681379/78023296-11721d00-735f-11ea-8fbc-99522b7f6ebe.png)

**Comment by sdzhepa** [comment]
Thank you @engcom-Delta 

New task is created to cover missed points https://github.com/magento/magento2-login-as-customer/issues/55

cc: @naydav and @mbrinton01
