### ISSUE TITLE
[QA] Website selector for multiple websites (verification)

### ISSUE THREAD

**Issue by naydav** [magento/magento2-login-as-customer#32]
Need to verify that after merging of the initial module we have:

As a merchant admin user I want to choose which website I log in to as a customer so that I can assist customers with purchasing from the correct website.

**Current State**
In the MageFan extension there is an option to require the admin user to select a Store View / Website when logging into a customer account. This was added in version 2.2.0 of the extension.

**Business Value**
Merchants who manage multiple websites on a single Magento instance often have very different sites enabled. For example, they could have sites for entirely different brands, customers, or regions. To provide support for customers, merchants with multiple websites need to be able to select which website to view when using the Login as Customer feature.

**Assumptions and Notes**
 * This feature already exists in the MageFan extension. It needs to be validated against the AC.

**AC**
 * When the 'Store View To Log In' setting = 'Manual Choose' admin user is prompted to select a website after they click the Login as Customer button/link
 * Selector matches approved UX design
 * Admin user is logged into the correct site based on selection made

**Out of Scope**
 * None defined

**Demo Steps**
 1. <span style="color:#00875a"><AUTOMATED></span> Login as admin user to admin panel
 1. <span style="color:#00875a">[AUTOMATED]</span> Verify multiple websites are enabled
 1. <span style="color:#00875a">[AUTOMATED]</span> Ensure 'Store View To Log In' setting = 'Manual Choose' # <span style="color:#00875a">[AUTOMATED]</span> As the admin user, Log in as Customer
 1. <span style="color:#00875a">[AUTOMATED]</span> Verify website selector appears
 1. <span style="color:#00875a">[AUTOMATED]</span> Select a website
 1. <span style="color:#00875a">[AUTOMATED]</span> Verify Login occurs to correct website and customer account in a separate window/tab
 1. <span style="color:#00875a">[AUTOMATED]</span> Ensure 'Store View To Log In' setting = 'Auto-detection'
 1. <span style="color:#00875a">[AUTOMATED]</span> As the admin user, Log in as Customer
 1. <span style="color:#00875a">[AUTOMATED]</span> Verify website selector does not appear
 1. <span style="color:#00875a">[AUTOMATED]</span> Verify Login occurs to correct website and customer account in a separate window/tab
     1. If customer accounts are global, log in is made to default website
     1. If customer accounts are per website, log in is made to the website the customer account is assigned to

**Comment by engcom-Delta** [comment]
Verification results:

**AC**

 * Selector matches approved UX design - **Result:** store view switcher opens in new tab - [ **dev task** ]:  https://github.com/magento/magento2-login-as-customer/issues/54
![image](https://user-images.githubusercontent.com/51681379/78030231-6c5d4180-736a-11ea-9d4f-2f0a19dd8a83.png)

**Demo Steps**

 1. <span style="color:#00875a">[AUTOMATED]</span> Verify website selector appears  - **Result:** store view switcher opens in new tab - [ **dev task** ]:  https://github.com/magento/magento2-login-as-customer/issues/54
![image](https://user-images.githubusercontent.com/51681379/78030231-6c5d4180-736a-11ea-9d4f-2f0a19dd8a83.png)

 1. <span style="color:#00875a">[AUTOMATED]</span> Verify website selector does not appear - **Result:** redirects to storefronts without confirmation popup -  [ **dev task** ]:  https://github.com/magento/magento2-login-as-customer/issues/54
![image](https://user-images.githubusercontent.com/51681379/78031633-7b44f380-736c-11ea-9293-adc3cfa83c4f.png)

 1. <span style="color:#00875a">[AUTOMATED]</span> Verify Login occurs to correct website and customer account in a separate window/tab
     1. If customer accounts are global, log in is made to default website - **Result:** log in is made to the website the customer account is assigned to - [ **no dev task created** ]

**Comment by sdzhepa** [comment]
Thank you @engcom-Delta 

New dev tasks based on your verification are created:
1. https://github.com/magento/magento2-login-as-customer/issues/56 Pop-up window for Manual mode
2. https://github.com/magento/magento2-login-as-customer/issues/57 Pop-up window for Auto mode

cc: @naydav @mbrinton01
