### ISSUE TITLE
Remove option to merge guest cart

### ISSUE THREAD

**Issue by naydav** [magento/magento2-login-as-customer#34]
As a merchant I want to remove the possibility of merging guest carts with Login as Customer session carts so that customer service reps cannot accidentally add unexpected items to customer carts.

**Business Value**
Merging products to a customer's cart from a separate guest cart (in another tab or window) does not make business sense in nearly every case, and has the possibility to put items in a customer's cart that the admin user did not expect. Even if an admin user would like to add products to a customer's cart, there are multiple ways to do this, including:
 * Add to cart from admin panel
 * Login as Customer and add to cart from category page, product page, quick order, or reorder

Because of these possible workarounds as well as the potential for error, this setting should be removed.

**Assumptions and Notes**
 * Desired behavior is already implemented by code used for `No` setting of 'Keep Guest Shopping Cart Items'

**AC**
 * 'Keep Guest Shopping Cart Items' setting is removed from admin panel (see attached screenshot 'remove merge.png')
 * If an admin user creates a Login as Customer session for a customer and has a preexisting guest cart containing products, no products are merged with the customer's cart
 * Any current user message or confirmation for merging carts is removed from the UI

**Demo Steps**
 1. Open admin panel and show that 'Keep Guest Shopping Cart Items' setting is removed
 1. Open tab with guest cart and add products to guest cart
 1. From admin panel, view contents of a customer cart
 1. From admin panel, Login as same Customer
 1. Verify that contents of the customer cart have not changed

**Comment by naydav** [comment]
https://github.com/magento/magento2-login-as-customer/pull/49

**Comment by engcom-Delta** [comment]
:heavy_check_mark:  Issue is not reproducible according **Demo Steps** with latest commit [9204ab7](https://github.com/magento/magento2-login-as-customer/commit/9204ab78f6f69cd1f8a0bf496a58fb36b3486eb5)
![image](https://user-images.githubusercontent.com/51681379/79865654-2ed95a80-83e4-11ea-880d-c0609e0cf1e1.png)
