### ISSUE TITLE
UX DESIGN in one place

### ISSUE THREAD

**Issue by sdzhepa** [magento/magento2-login-as-customer#54]
One task with all UX materials

### Full design documents
- **UX design PDF:** [UX_LoginAsCustomer_March_12_3_2020.pdf](https://github.com/magento/magento2-login-as-customer/files/4325537/UX_LoginAsCustomer_March_12_3_2020.pdf)
- all UX design mockup : https://xd.adobe.com/view/b9d43ac6-ee9f-4e94-516a-70dd15b45232-cfe5/grid

### Norification Banner
- [Notification banner UX design](https://xd.adobe.com/view/7c1347fc-d229-4afc-5ee7-1c53bdaec588-0a22/)
- [Notification banner UX design PDF](https://github.com/magento/magento2-login-as-customer/files/4388646/BannerAdditionalDesignDetails.pdf)

**Comment by engcom-tester** [comment]
@magento I am working on it

**Comment by engcom-tester** [comment]
@magento I am working on it
