### ISSUE TITLE
[DEV] Need to update/change titles for ACL resource tree related to Login as Customer 

### ISSUE THREAD

**Issue by sdzhepa** [magento/magento2-login-as-customer#55]
After work on QA verification task for https://github.com/magento/magento2-login-as-customer/issues/31 were defined a couple of points that not implemented/updated yet but should be.
Points were described in https://github.com/magento/magento2-login-as-customer/issues/31#issuecomment-606596330

#### Implementation task
All titles in ACL tree related to "Login as Customer" should be the same as on [UX Design](https://xd.adobe.com/view/b9d43ac6-ee9f-4e94-516a-70dd15b45232-cfe5/screen/f9a6b145-1933-4791-801b-3bdbe0a41933/Configuration)
![acl_login_](https://user-images.githubusercontent.com/3409584/78059710-f5b34a80-734f-11ea-82a5-186b0be43db4.png)

1. "Login **As** Customer" should be changed to "Login **as** Customer"
2. "Allow Login As Customer Button" => "Allow Login **as** Customer Button"
3. "Login As Customer Log" => "**View** Login **as** Customer Log"
4.  "Login As Customer Section" => "Login **as** Customer Section"

#### QA after implementation
1. Verify and confirm that all titles(text) are equal as on UX design
2. Verify and confirm that all AC from https://github.com/magento/magento2-login-as-customer/issues/31 are meet and demo scenario can be passed as described
3. Chech if need update/add any new test-cases into [Login as Customer](https://studio.cucumber.io/projects/163172/test-plan/folders/1204738) HipTest(Cucumber Studio) project

**Comment by naydav** [comment]
https://github.com/magento/magento2-login-as-customer/pull/69

**Comment by engcom-Delta** [comment]
:heavy_check_mark: Issue is fixed
Result with latest commit [9204ab7](https://github.com/magento/magento2-login-as-customer/commit/9204ab78f6f69cd1f8a0bf496a58fb36b3486eb5)

![image](https://user-images.githubusercontent.com/51681379/79867638-53830180-83e7-11ea-81ad-1ed26f99e5ad.png)

![image](https://user-images.githubusercontent.com/51681379/79867936-d1dfa380-83e7-11ea-9230-879d2e26b2da.png)
