### ISSUE TITLE
[DEV] Confirmation pop-up window for "Login as Customer" if the setting "Store View To Log In" = "Manual Chooser"

### ISSUE THREAD

**Issue by sdzhepa** [magento/magento2-login-as-customer#56]
After work on QA verification task for https://github.com/magento/magento2-login-as-customer/issues/31 were defined a couple of points that not implemented/updated yet but should be.
Points were described in https://github.com/magento/magento2-login-as-customer/issues/32#issuecomment-606633297

#### Implementation task
According to [UX design](https://xd.adobe.com/view/b9d43ac6-ee9f-4e94-516a-70dd15b45232-cfe5/screen/4300100f-4447-462c-87ff-1a1d1ce310ee/Website-selector-manual) pop-up window should be implemented.
_Note:  The window(pop-up) should appear only if the setting "Store View To Log in" = "Namual Chooser" in Configuration_

![chooser](https://user-images.githubusercontent.com/3409584/78061849-732c8a00-7353-11ea-87d5-e8f1608a16b2.png)

#### QA after implementation
1. Verify and confirm that "Select Store" pop-up window is implemented as on UX design and works as expected.
2. Verify and confirm that all AC from https://github.com/magento/magento2-login-as-customer/issues/32 are meet and demo scenario can be passed as described
3. Chech if need update/add any new test-cases into [Login as Customer](https://studio.cucumber.io/projects/163172/test-plan/folders/1204738) HipTest(Cucumber Studio) project

**Comment by ihorvansach** [comment]
Working on it
