### ISSUE TITLE
[DEV] Confirmation pop-up window for "Login as Customer" if the setting "Store View To Log In" = "Automatic"

### ISSUE THREAD

**Issue by sdzhepa** [magento/magento2-login-as-customer#57]
After work on QA verification task for https://github.com/magento/magento2-login-as-customer/issues/31 were defined a couple of points that not implemented/updated yet but should be.
Points were described in https://github.com/magento/magento2-login-as-customer/issues/32#issuecomment-606633297

#### Implementation task
According to [UX design](https://xd.adobe.com/view/b9d43ac6-ee9f-4e94-516a-70dd15b45232-cfe5/screen/03bd2e61-7ade-48e2-9a29-61bd6850c93b/Website-selector-automatic) pop-up window should be implemented.
_Note:  The window(pop-up) should appear only if the setting "Store View To Log in" = "Automatic" in Configuration_

![automatic](https://user-images.githubusercontent.com/3409584/78062691-ae7b8880-7354-11ea-8bfd-966224abda93.png)

#### QA after implementation
1. Verify and confirm that  pop-up window is implemented as on UX design and works as expected.
2. Verify and confirm that all AC from https://github.com/magento/magento2-login-as-customer/issues/32 are meet and demo scenario can be passed as described
3. Chech if need update/add any new test-cases into [Login as Customer](https://studio.cucumber.io/projects/163172/test-plan/folders/1204738) HipTest(Cucumber Studio) project

**Comment by ihorvansach** [comment]
Working on it
