### ISSUE TITLE
 Login As Customer functionality is available when Login As Customer->Enable Extension=No 

### ISSUE THREAD

**Issue by VasylShvorak** [magento/magento2-login-as-customer#71]
### Preconditions (*)

1. Magento with Login As Customer extension
2. Customer is created

### Steps to reproduce (*)

1. Go to Stores->Configuration->Customers->Login As Customer
2. Set Enable Extension=No
3. Flush Magento Caches
4. Go to Customers->All Customers
5. Click Edit on existing customer

### Expected result (*)

1. Button "Login as Customer" is not shown
2. Link to "Login as Customer Log" is now shown in menu. _CUSTOMERS > Login as Customer Log_
2. Login as Customer functionality is not available in Admin Panel

### Actual result (*)

1. Button Login as Customer is not shown
2. All  Login As Customer functionality is available for admin that leads to exception error

**Comment by sdzhepa** [comment]
@naydav @ihor-sviziev @engcom-Delta @engcom-Foxtrot 

Reopened due to lates QA testing.
Issue still can be reproduced
