### ISSUE TITLE
Page title is empty when admin login as customer

### ISSUE THREAD

**Issue by VasylShvorak** [magento/magento2-login-as-customer#73]
### Preconditions (*)

1. Magento with Login As Customer extension
2. Customer is created

### Steps to reproduce (*)

1. Go to Customers->All Customers
2. Click Edit on existing customer
3. Click on **Login as Customer** button

### Expected result (*)

1. Page title should not be empty

### Actual result (*)

1. Page title is empty and page url is shown
![image](https://user-images.githubusercontent.com/26908019/79124398-e77c1a00-7da4-11ea-935e-e9bd98f79f58.png)

**Comment by naydav** [comment]
https://github.com/magento/magento2-login-as-customer/pull/92
