### ISSUE TITLE
Uncorrect welcome message is shown when admin login as customer

### ISSUE THREAD

**Issue by VasylShvorak** [magento/magento2-login-as-customer#74]
### Preconditions (*)

1. Magento with Login As Customer extension
2. Customer is created

### Steps to reproduce (*)

1. Go to Customers->All Customers
2. Click Edit on existing customer
3. Click on **Login as Customer** button

### Expected result (*)

1. Welcome message contains customer's first name and last name

### Actual result (*)

1. Default welcome message is shown
![LoginAsCustomerIssue](https://user-images.githubusercontent.com/26908019/79124790-c1a34500-7da5-11ea-8233-46f38ef76f6e.png)

**Comment by engcom-Delta** [comment]
Issue is not reproducible due to https://github.com/magento/magento2-login-as-customer/pull/87
Current behavior:
![image](https://user-images.githubusercontent.com/51681379/80354192-13a49a00-887f-11ea-9be7-52b0e42d9e50.png)
