### ISSUE TITLE
"Login as Customer" button must be next to the “Back button” on the left

### ISSUE THREAD

**Issue by sdzhepa** [magento/magento2-login-as-customer#94]
According to [UX design](https://xd.adobe.com/view/b9d43ac6-ee9f-4e94-516a-70dd15b45232-cfe5/grid/): 

> we want to keep consistency btw the Order page and the Customer page the button should be on the same position (next to the back button). On the order page the “Login as customer” button is on the right position.

### Preconditions (*)

1. Test customer is created

### Steps to reproduce (*)

1. Login to Admin Panel
2. Go to CUSTOMERS > All Customers
3. Click from grid te open Customer Details page

### Expected result (*)

1. According to [UX design for Customer Details page](https://xd.adobe.com/view/b9d43ac6-ee9f-4e94-516a-70dd15b45232-cfe5/screen/703b553d-7f57-4fec-9182-c435b73ba5a9/Customer-page-2?fullscreen)

![ExpectedButtonPosition](https://user-images.githubusercontent.com/3409584/80243568-127c2e80-862d-11ea-90fa-7662369581f1.png)

### Actual result (*)
![ActualButtonPosition](https://user-images.githubusercontent.com/3409584/80243718-52dbac80-862d-11ea-9b64-27bdd51ac08d.png)

**Comment by naydav** [comment]
https://github.com/magento/magento2-login-as-customer/pull/143

**Comment by naydav** [comment]
Remerged https://github.com/magento/magento2-login-as-customer/pull/166
