### ISSUE TITLE
Incorrect text value. In all places should be used "Login as Customer"  instead of "Login As Customer"

### ISSUE THREAD

**Issue by sdzhepa** [magento/magento2-login-as-customer#95]
This task should be already done in the scope of other PR currently in the queue.
Approach, using Search and Replace find all places with "login as customer" and change them to the correct value "Login as Customer"

Create this issue just for testing purposes and listed places where it should be checked

![TextLogin_as_Customer](https://user-images.githubusercontent.com/3409584/80244399-76ebbd80-862e-11ea-8cb5-9745b5167dd7.png)
![TextLogin_as_Customer_sysConf](https://user-images.githubusercontent.com/3409584/80244408-79e6ae00-862e-11ea-995c-74db4d7ba984.png)

![TextLogin_as_Customer_manu](https://user-images.githubusercontent.com/3409584/80245116-b8309d00-862f-11ea-97ac-6546faaa6cc4.png)

**Comment by naydav** [comment]
https://github.com/magento/magento2-login-as-customer/pull/138
